USE HuskyHub;
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (93, 76, null, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 5.50, null, 'http://noaa.gov/ipsum/primis/in/faucibus/orci/luctus/et.js?sit=leo&amet=rhoncus&eros=sed&suspendisse=vestibulum&accumsan=sit&tortor=amet&quis=cursus&turpis=id&sed=turpis&ante=integer&vivamus=aliquet&tortor=massa&duis=id&mattis=lobortis&egestas=convallis&metus=tortor&aenean=risus&fermentum=dapibus&donec=augue&ut=vel&mauris=accumsan&eget=tellus&massa=nisi&tempor=eu&convallis=orci&nulla=mauris&neque=lacinia&libero=sapien&convallis=quis&eget=libero&eleifend=nullam&luctus=sit&ultricies=amet&eu=turpis&nibh=elementum&quisque=ligula&id=vehicula&justo=consequat&sit=morbi&amet=a&sapien=ipsum&dignissim=integer&vestibulum=a&vestibulum=nibh&ante=in&ipsum=quis&primis=justo&in=maecenas&faucibus=rhoncus&orci=aliquam&luctus=lacus&et=morbi&ultrices=quis&posuere=tortor&cubilia=id&curae=nulla&nulla=ultrices&dapibus=aliquet&dolor=maecenas&vel=leo', '2025-05-15 08:24:50', '2025-04-27 12:23:32', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (54, 1, null, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 3.72, null, 'http://cdc.gov/sit/amet/consectetuer/adipiscing/elit/proin.png?accumsan=felis&tellus=sed&nisi=lacus&eu=morbi&orci=sem&mauris=mauris&lacinia=laoreet&sapien=ut&quis=rhoncus&libero=aliquet&nullam=pulvinar&sit=sed&amet=nisl&turpis=nunc&elementum=rhoncus&ligula=dui&vehicula=vel&consequat=sem&morbi=sed&a=sagittis&ipsum=nam&integer=congue&a=risus&nibh=semper&in=porta&quis=volutpat&justo=quam&maecenas=pede&rhoncus=lobortis&aliquam=ligula&lacus=sit&morbi=amet&quis=eleifend&tortor=pede&id=libero&nulla=quis&ultrices=orci&aliquet=nullam&maecenas=molestie&leo=nibh&odio=in&condimentum=lectus&id=pellentesque&luctus=at&nec=nulla&molestie=suspendisse&sed=potenti&justo=cras&pellentesque=in&viverra=purus&pede=eu&ac=magna&diam=vulputate&cras=luctus&pellentesque=cum&volutpat=sociis&dui=natoque&maecenas=penatibus&tristique=et&est=magnis&et=dis&tempus=parturient&semper=montes&est=nascetur&quam=ridiculus&pharetra=mus&magna=vivamus&ac=vestibulum&consequat=sagittis&metus=sapien&sapien=cum&ut=sociis&nunc=natoque&vestibulum=penatibus&ante=et&ipsum=magnis&primis=dis&in=parturient&faucibus=montes&orci=nascetur', '2025-03-31 15:54:04', '2025-08-04 23:02:16', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (25, 52, null, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 8.75, null, 'http://soundcloud.com/nec/molestie.png?interdum=sapien&mauris=cursus&non=vestibulum&ligula=proin&pellentesque=eu&ultrices=mi&phasellus=nulla&id=ac&sapien=enim&in=in&sapien=tempor&iaculis=turpis&congue=nec&vivamus=euismod&metus=scelerisque&arcu=quam&adipiscing=turpis&molestie=adipiscing&hendrerit=lorem&at=vitae&vulputate=mattis&vitae=nibh&nisl=ligula&aenean=nec&lectus=sem&pellentesque=duis&eget=aliquam&nunc=convallis&donec=nunc&quis=proin&orci=at&eget=turpis&orci=a&vehicula=pede&condimentum=posuere&curabitur=nonummy&in=integer&libero=non&ut=velit', '2025-02-14 09:28:37', '2024-12-28 17:57:06', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (87, 31, null, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 5.40, null, 'https://whitehouse.gov/elit/sodales/scelerisque/mauris.jsp?eu=convallis&mi=tortor&nulla=risus&ac=dapibus&enim=augue&in=vel&tempor=accumsan&turpis=tellus&nec=nisi&euismod=eu&scelerisque=orci&quam=mauris&turpis=lacinia&adipiscing=sapien&lorem=quis&vitae=libero&mattis=nullam&nibh=sit&ligula=amet&nec=turpis&sem=elementum&duis=ligula&aliquam=vehicula&convallis=consequat&nunc=morbi&proin=a&at=ipsum&turpis=integer&a=a&pede=nibh&posuere=in&nonummy=quis&integer=justo&non=maecenas&velit=rhoncus&donec=aliquam&diam=lacus&neque=morbi&vestibulum=quis&eget=tortor&vulputate=id&ut=nulla&ultrices=ultrices&vel=aliquet&augue=maecenas&vestibulum=leo&ante=odio&ipsum=condimentum&primis=id&in=luctus&faucibus=nec&orci=molestie&luctus=sed&et=justo&ultrices=pellentesque&posuere=viverra&cubilia=pede&curae=ac&donec=diam&pharetra=cras&magna=pellentesque&vestibulum=volutpat&aliquet=dui&ultrices=maecenas&erat=tristique', '2025-06-11 02:01:23', '2025-11-17 15:16:02', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (8, 19, null, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1.14, null, 'https://cisco.com/magna/vulputate.js?vestibulum=tortor&sit=duis&amet=mattis&cursus=egestas&id=metus&turpis=aenean&integer=fermentum&aliquet=donec&massa=ut&id=mauris&lobortis=eget&convallis=massa&tortor=tempor&risus=convallis&dapibus=nulla&augue=neque&vel=libero&accumsan=convallis&tellus=eget&nisi=eleifend&eu=luctus&orci=ultricies&mauris=eu&lacinia=nibh&sapien=quisque&quis=id&libero=justo&nullam=sit&sit=amet&amet=sapien&turpis=dignissim&elementum=vestibulum&ligula=vestibulum&vehicula=ante&consequat=ipsum&morbi=primis&a=in&ipsum=faucibus&integer=orci&a=luctus&nibh=et&in=ultrices&quis=posuere&justo=cubilia&maecenas=curae&rhoncus=nulla&aliquam=dapibus&lacus=dolor&morbi=vel&quis=est&tortor=donec&id=odio&nulla=justo&ultrices=sollicitudin&aliquet=ut&maecenas=suscipit&leo=a&odio=feugiat&condimentum=et&id=eros&luctus=vestibulum&nec=ac&molestie=est&sed=lacinia&justo=nisi&pellentesque=venenatis&viverra=tristique&pede=fusce&ac=congue&diam=diam&cras=id&pellentesque=ornare&volutpat=imperdiet&dui=sapien&maecenas=urna&tristique=pretium&est=nisl', '2025-03-24 08:54:06', '2025-04-09 00:48:46', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (99, 23, null, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 0.64, null, 'http://businessweek.com/vestibulum.html?nulla=a&nisl=odio&nunc=in&nisl=hac&duis=habitasse&bibendum=platea&felis=dictumst&sed=maecenas&interdum=ut&venenatis=massa&turpis=quis&enim=augue&blandit=luctus&mi=tincidunt&in=nulla&porttitor=mollis&pede=molestie&justo=lorem&eu=quisque&massa=ut&donec=erat&dapibus=curabitur&duis=gravida&at=nisi&velit=at&eu=nibh&est=in&congue=hac&elementum=habitasse&in=platea&hac=dictumst&habitasse=aliquam&platea=augue&dictumst=quam&morbi=sollicitudin&vestibulum=vitae&velit=consectetuer&id=eget&pretium=rutrum&iaculis=at&diam=lorem&erat=integer&fermentum=tincidunt&justo=ante&nec=vel&condimentum=ipsum&neque=praesent&sapien=blandit&placerat=lacinia&ante=erat&nulla=vestibulum&justo=sed&aliquam=magna&quis=at&turpis=nunc', '2025-04-25 17:19:02', '2025-01-27 11:26:48', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (36, 8, null, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 2.91, null, 'http://wordpress.org/ullamcorper/purus/sit/amet/nulla/quisque.xml?viverra=augue&eget=vestibulum&congue=rutrum&eget=rutrum&semper=neque&rutrum=aenean&nulla=auctor&nunc=gravida&purus=sem&phasellus=praesent&in=id&felis=massa&donec=id&semper=nisl&sapien=venenatis&a=lacinia&libero=aenean&nam=sit&dui=amet&proin=justo&leo=morbi&odio=ut&porttitor=odio&id=cras&consequat=mi&in=pede&consequat=malesuada&ut=in&nulla=imperdiet&sed=et&accumsan=commodo&felis=vulputate&ut=justo&at=in&dolor=blandit&quis=ultrices&odio=enim&consequat=lorem&varius=ipsum&integer=dolor&ac=sit&leo=amet&pellentesque=consectetuer&ultrices=adipiscing&mattis=elit&odio=proin&donec=interdum&vitae=mauris&nisi=non&nam=ligula&ultrices=pellentesque&libero=ultrices&non=phasellus&mattis=id&pulvinar=sapien&nulla=in&pede=sapien&ullamcorper=iaculis&augue=congue&a=vivamus&suscipit=metus&nulla=arcu&elit=adipiscing&ac=molestie&nulla=hendrerit&sed=at&vel=vulputate&enim=vitae&sit=nisl&amet=aenean&nunc=lectus&viverra=pellentesque&dapibus=eget&nulla=nunc&suscipit=donec&ligula=quis&in=orci&lacus=eget&curabitur=orci&at=vehicula&ipsum=condimentum&ac=curabitur&tellus=in&semper=libero&interdum=ut&mauris=massa&ullamcorper=volutpat&purus=convallis&sit=morbi&amet=odio&nulla=odio&quisque=elementum&arcu=eu', '2025-11-25 04:47:23', '2025-01-26 11:45:22', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (64, 52, null, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 5.52, null, 'http://feedburner.com/enim/in/tempor/turpis/nec/euismod/scelerisque.html?augue=est&luctus=congue&tincidunt=elementum&nulla=in&mollis=hac&molestie=habitasse&lorem=platea&quisque=dictumst&ut=morbi&erat=vestibulum&curabitur=velit&gravida=id&nisi=pretium&at=iaculis&nibh=diam&in=erat&hac=fermentum&habitasse=justo&platea=nec&dictumst=condimentum&aliquam=neque&augue=sapien', '2025-04-22 17:29:09', '2025-07-23 22:52:53', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (48, 86, null, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 8.12, null, 'http://jiathis.com/ipsum/primis/in.png?vitae=aliquet&consectetuer=maecenas&eget=leo&rutrum=odio&at=condimentum&lorem=id&integer=luctus&tincidunt=nec&ante=molestie&vel=sed&ipsum=justo&praesent=pellentesque&blandit=viverra&lacinia=pede&erat=ac&vestibulum=diam&sed=cras&magna=pellentesque&at=volutpat&nunc=dui&commodo=maecenas&placerat=tristique', '2025-09-09 09:06:56', '2025-05-18 05:03:53', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (94, 11, null, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.

In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 0.21, null, 'https://spotify.com/ut/massa/volutpat.js?sed=at&ante=vulputate&vivamus=vitae&tortor=nisl&duis=aenean&mattis=lectus&egestas=pellentesque&metus=eget&aenean=nunc&fermentum=donec&donec=quis&ut=orci&mauris=eget&eget=orci&massa=vehicula&tempor=condimentum&convallis=curabitur&nulla=in&neque=libero&libero=ut&convallis=massa&eget=volutpat&eleifend=convallis&luctus=morbi&ultricies=odio&eu=odio&nibh=elementum&quisque=eu&id=interdum&justo=eu&sit=tincidunt&amet=in&sapien=leo&dignissim=maecenas&vestibulum=pulvinar&vestibulum=lobortis&ante=est&ipsum=phasellus&primis=sit&in=amet&faucibus=erat&orci=nulla&luctus=tempus&et=vivamus&ultrices=in&posuere=felis&cubilia=eu&curae=sapien&nulla=cursus&dapibus=vestibulum&dolor=proin&vel=eu&est=mi&donec=nulla&odio=ac&justo=enim&sollicitudin=in&ut=tempor&suscipit=turpis&a=nec&feugiat=euismod&et=scelerisque&eros=quam&vestibulum=turpis&ac=adipiscing&est=lorem&lacinia=vitae&nisi=mattis&venenatis=nibh', '2025-05-08 11:04:53', '2025-01-06 19:44:43', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (66, 47, null, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 0.08, null, 'http://cpanel.net/tincidunt/in.jpg?accumsan=ut&odio=nunc&curabitur=vestibulum&convallis=ante&duis=ipsum&consequat=primis&dui=in&nec=faucibus&nisi=orci&volutpat=luctus&eleifend=et&donec=ultrices&ut=posuere&dolor=cubilia&morbi=curae&vel=mauris&lectus=viverra&in=diam&quam=vitae&fringilla=quam&rhoncus=suspendisse&mauris=potenti&enim=nullam&leo=porttitor&rhoncus=lacus&sed=at&vestibulum=turpis&sit=donec&amet=posuere&cursus=metus&id=vitae&turpis=ipsum&integer=aliquam&aliquet=non&massa=mauris&id=morbi&lobortis=non&convallis=lectus&tortor=aliquam&risus=sit&dapibus=amet&augue=diam&vel=in&accumsan=magna&tellus=bibendum&nisi=imperdiet&eu=nullam&orci=orci&mauris=pede&lacinia=venenatis&sapien=non&quis=sodales&libero=sed&nullam=tincidunt&sit=eu&amet=felis&turpis=fusce&elementum=posuere&ligula=felis&vehicula=sed&consequat=lacus&morbi=morbi&a=sem&ipsum=mauris&integer=laoreet&a=ut&nibh=rhoncus', '2025-01-29 13:35:56', '2025-07-23 10:09:28', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (94, 97, null, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 4.02, null, 'http://icio.us/justo/eu/massa.png?lacus=ipsum&purus=primis', '2025-02-10 11:35:13', '2025-02-26 03:07:23', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (57, 99, null, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 0.59, null, 'https://answers.com/vel/ipsum/praesent/blandit.jpg?nec=in&nisi=congue&volutpat=etiam&eleifend=justo&donec=etiam&ut=pretium&dolor=iaculis&morbi=justo&vel=in&lectus=hac&in=habitasse&quam=platea&fringilla=dictumst&rhoncus=etiam&mauris=faucibus&enim=cursus&leo=urna&rhoncus=ut&sed=tellus&vestibulum=nulla&sit=ut&amet=erat&cursus=id&id=mauris&turpis=vulputate&integer=elementum&aliquet=nullam&massa=varius&id=nulla&lobortis=facilisi&convallis=cras&tortor=non&risus=velit&dapibus=nec&augue=nisi&vel=vulputate&accumsan=nonummy&tellus=maecenas&nisi=tincidunt&eu=lacus&orci=at&mauris=velit&lacinia=vivamus&sapien=vel&quis=nulla&libero=eget&nullam=eros&sit=elementum&amet=pellentesque&turpis=quisque&elementum=porta', '2025-02-20 18:55:51', '2025-09-07 02:28:56', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (62, 47, null, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 0.56, null, 'http://msu.edu/integer/tincidunt/ante/vel/ipsum.html?a=turpis&ipsum=elementum&integer=ligula&a=vehicula&nibh=consequat&in=morbi&quis=a&justo=ipsum&maecenas=integer&rhoncus=a&aliquam=nibh&lacus=in&morbi=quis&quis=justo&tortor=maecenas&id=rhoncus&nulla=aliquam&ultrices=lacus&aliquet=morbi&maecenas=quis&leo=tortor&odio=id&condimentum=nulla&id=ultrices&luctus=aliquet', '2025-11-08 05:21:44', '2025-03-05 21:05:19', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (33, 42, null, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 3.72, null, 'https://wix.com/ultrices/erat/tortor/sollicitudin/mi/sit/amet.png?nulla=lobortis&suspendisse=convallis&potenti=tortor&cras=risus&in=dapibus&purus=augue&eu=vel&magna=accumsan&vulputate=tellus&luctus=nisi&cum=eu&sociis=orci&natoque=mauris&penatibus=lacinia&et=sapien&magnis=quis&dis=libero&parturient=nullam&montes=sit', '2025-10-22 06:24:40', '2025-09-05 15:23:22', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (84, 96, null, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 6.50, null, 'https://ebay.com/eleifend/pede/libero/quis/orci/nullam/molestie.json?at=mauris&velit=viverra&vivamus=diam&vel=vitae&nulla=quam&eget=suspendisse&eros=potenti&elementum=nullam&pellentesque=porttitor&quisque=lacus&porta=at&volutpat=turpis&erat=donec&quisque=posuere&erat=metus&eros=vitae&viverra=ipsum&eget=aliquam&congue=non&eget=mauris&semper=morbi&rutrum=non&nulla=lectus&nunc=aliquam&purus=sit&phasellus=amet&in=diam&felis=in&donec=magna&semper=bibendum&sapien=imperdiet&a=nullam&libero=orci&nam=pede&dui=venenatis&proin=non&leo=sodales&odio=sed&porttitor=tincidunt&id=eu&consequat=felis&in=fusce&consequat=posuere&ut=felis&nulla=sed&sed=lacus&accumsan=morbi&felis=sem&ut=mauris&at=laoreet&dolor=ut&quis=rhoncus&odio=aliquet&consequat=pulvinar&varius=sed&integer=nisl&ac=nunc&leo=rhoncus&pellentesque=dui&ultrices=vel&mattis=sem&odio=sed&donec=sagittis&vitae=nam&nisi=congue&nam=risus&ultrices=semper&libero=porta&non=volutpat&mattis=quam&pulvinar=pede&nulla=lobortis&pede=ligula&ullamcorper=sit&augue=amet&a=eleifend&suscipit=pede&nulla=libero&elit=quis&ac=orci&nulla=nullam&sed=molestie&vel=nibh&enim=in&sit=lectus&amet=pellentesque', '2025-05-15 05:57:00', '2025-05-20 00:34:33', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (67, 94, null, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 8.45, null, 'http://infoseek.co.jp/cubilia/curae/donec/pharetra/magna/vestibulum.js?ultrices=eu&posuere=orci', '2025-10-26 06:20:52', '2025-12-02 15:26:42', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (7, 6, null, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1.87, null, 'https://printfriendly.com/erat/curabitur/gravida.aspx?dapibus=dis&duis=parturient&at=montes&velit=nascetur&eu=ridiculus&est=mus&congue=etiam&elementum=vel', '2025-08-05 11:54:26', '2025-10-04 00:52:25', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (65, 77, null, 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 0.37, null, 'http://shutterfly.com/magna/vulputate/luctus/cum.jsp?porttitor=neque&lacus=duis&at=bibendum&turpis=morbi&donec=non&posuere=quam&metus=nec&vitae=dui&ipsum=luctus&aliquam=rutrum', '2025-01-21 04:00:57', '2025-04-08 21:41:41', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (98, 13, null, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 8.63, null, 'http://elpais.com/ultrices/posuere/cubilia/curae/donec/pharetra/magna.xml?nibh=id&in=consequat&quis=in&justo=consequat&maecenas=ut&rhoncus=nulla&aliquam=sed&lacus=accumsan&morbi=felis&quis=ut&tortor=at&id=dolor&nulla=quis&ultrices=odio&aliquet=consequat&maecenas=varius&leo=integer&odio=ac&condimentum=leo&id=pellentesque&luctus=ultrices&nec=mattis&molestie=odio&sed=donec&justo=vitae&pellentesque=nisi&viverra=nam&pede=ultrices&ac=libero&diam=non&cras=mattis&pellentesque=pulvinar&volutpat=nulla&dui=pede&maecenas=ullamcorper&tristique=augue&est=a&et=suscipit&tempus=nulla&semper=elit&est=ac&quam=nulla&pharetra=sed', '2025-01-05 17:39:09', '2025-09-26 15:55:23', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (34, 85, null, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.

Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 5.88, null, 'http://csmonitor.com/dapibus/at/diam/nam/tristique/tortor/eu.jsp?habitasse=suspendisse&platea=potenti&dictumst=in&morbi=eleifend&vestibulum=quam&velit=a&id=odio&pretium=in&iaculis=hac&diam=habitasse&erat=platea&fermentum=dictumst&justo=maecenas&nec=ut&condimentum=massa&neque=quis&sapien=augue&placerat=luctus&ante=tincidunt&nulla=nulla&justo=mollis&aliquam=molestie&quis=lorem&turpis=quisque&eget=ut&elit=erat&sodales=curabitur&scelerisque=gravida&mauris=nisi&sit=at&amet=nibh&eros=in&suspendisse=hac&accumsan=habitasse&tortor=platea&quis=dictumst&turpis=aliquam&sed=augue&ante=quam&vivamus=sollicitudin&tortor=vitae&duis=consectetuer&mattis=eget&egestas=rutrum&metus=at&aenean=lorem&fermentum=integer&donec=tincidunt&ut=ante&mauris=vel&eget=ipsum&massa=praesent&tempor=blandit&convallis=lacinia&nulla=erat&neque=vestibulum&libero=sed&convallis=magna&eget=at&eleifend=nunc&luctus=commodo&ultricies=placerat&eu=praesent&nibh=blandit&quisque=nam&id=nulla&justo=integer&sit=pede&amet=justo&sapien=lacinia&dignissim=eget&vestibulum=tincidunt&vestibulum=eget&ante=tempus&ipsum=vel&primis=pede&in=morbi&faucibus=porttitor&orci=lorem&luctus=id&et=ligula&ultrices=suspendisse&posuere=ornare&cubilia=consequat&curae=lectus&nulla=in&dapibus=est&dolor=risus&vel=auctor&est=sed&donec=tristique&odio=in&justo=tempus&sollicitudin=sit&ut=amet&suscipit=sem&a=fusce&feugiat=consequat&et=nulla', '2025-01-14 10:48:31', '2025-09-22 15:48:54', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (10, 80, null, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 8.33, null, 'https://hubpages.com/velit/nec/nisi/vulputate/nonummy.png?condimentum=at&curabitur=nibh&in=in&libero=hac&ut=habitasse&massa=platea&volutpat=dictumst&convallis=aliquam&morbi=augue&odio=quam&odio=sollicitudin&elementum=vitae&eu=consectetuer&interdum=eget&eu=rutrum&tincidunt=at&in=lorem&leo=integer&maecenas=tincidunt&pulvinar=ante&lobortis=vel&est=ipsum&phasellus=praesent&sit=blandit&amet=lacinia&erat=erat&nulla=vestibulum&tempus=sed&vivamus=magna&in=at&felis=nunc&eu=commodo&sapien=placerat&cursus=praesent&vestibulum=blandit&proin=nam&eu=nulla&mi=integer&nulla=pede&ac=justo&enim=lacinia&in=eget&tempor=tincidunt&turpis=eget&nec=tempus&euismod=vel&scelerisque=pede&quam=morbi&turpis=porttitor&adipiscing=lorem&lorem=id&vitae=ligula&mattis=suspendisse&nibh=ornare&ligula=consequat&nec=lectus&sem=in&duis=est&aliquam=risus&convallis=auctor&nunc=sed&proin=tristique&at=in&turpis=tempus&a=sit&pede=amet&posuere=sem&nonummy=fusce&integer=consequat&non=nulla&velit=nisl&donec=nunc&diam=nisl&neque=duis&vestibulum=bibendum&eget=felis&vulputate=sed&ut=interdum&ultrices=venenatis&vel=turpis&augue=enim&vestibulum=blandit&ante=mi&ipsum=in&primis=porttitor&in=pede&faucibus=justo&orci=eu&luctus=massa&et=donec', '2025-04-14 20:21:49', '2025-10-26 08:10:35', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (21, 13, null, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1.02, null, 'http://kickstarter.com/elementum/eu.xml?quam=donec&suspendisse=ut&potenti=dolor&nullam=morbi&porttitor=vel&lacus=lectus&at=in&turpis=quam&donec=fringilla&posuere=rhoncus&metus=mauris&vitae=enim&ipsum=leo&aliquam=rhoncus&non=sed&mauris=vestibulum&morbi=sit&non=amet&lectus=cursus&aliquam=id&sit=turpis&amet=integer&diam=aliquet&in=massa&magna=id&bibendum=lobortis&imperdiet=convallis&nullam=tortor&orci=risus&pede=dapibus&venenatis=augue&non=vel&sodales=accumsan&sed=tellus&tincidunt=nisi&eu=eu&felis=orci&fusce=mauris&posuere=lacinia&felis=sapien&sed=quis&lacus=libero&morbi=nullam', '2025-03-25 00:57:32', '2025-06-16 22:59:42', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (2, 89, null, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 6.21, null, 'http://ox.ac.uk/amet.aspx?porttitor=felis&lacus=fusce&at=posuere&turpis=felis&donec=sed&posuere=lacus&metus=morbi&vitae=sem&ipsum=mauris&aliquam=laoreet&non=ut&mauris=rhoncus&morbi=aliquet&non=pulvinar&lectus=sed&aliquam=nisl&sit=nunc&amet=rhoncus&diam=dui&in=vel&magna=sem&bibendum=sed&imperdiet=sagittis&nullam=nam&orci=congue&pede=risus&venenatis=semper&non=porta&sodales=volutpat&sed=quam&tincidunt=pede&eu=lobortis&felis=ligula&fusce=sit&posuere=amet&felis=eleifend&sed=pede&lacus=libero&morbi=quis&sem=orci&mauris=nullam&laoreet=molestie&ut=nibh&rhoncus=in&aliquet=lectus&pulvinar=pellentesque&sed=at&nisl=nulla&nunc=suspendisse&rhoncus=potenti&dui=cras&vel=in&sem=purus&sed=eu&sagittis=magna&nam=vulputate&congue=luctus&risus=cum&semper=sociis&porta=natoque', '2025-10-08 16:57:07', '2025-08-01 19:49:02', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (56, 56, null, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 7.35, null, 'http://dyndns.org/congue/etiam/justo.html?in=libero&est=convallis&risus=eget&auctor=eleifend&sed=luctus', '2025-02-24 13:29:32', '2025-07-11 14:19:05', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (19, 23, null, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 4.12, null, 'http://zdnet.com/eget/vulputate/ut/ultrices.js?nunc=augue&donec=a&quis=suscipit&orci=nulla&eget=elit&orci=ac&vehicula=nulla&condimentum=sed&curabitur=vel&in=enim&libero=sit&ut=amet&massa=nunc&volutpat=viverra&convallis=dapibus&morbi=nulla&odio=suscipit&odio=ligula&elementum=in&eu=lacus&interdum=curabitur&eu=at&tincidunt=ipsum&in=ac&leo=tellus&maecenas=semper&pulvinar=interdum&lobortis=mauris&est=ullamcorper&phasellus=purus&sit=sit&amet=amet&erat=nulla&nulla=quisque&tempus=arcu&vivamus=libero&in=rutrum', '2025-06-15 07:52:47', '2025-03-13 10:42:19', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (58, 8, null, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 8.42, null, 'https://artisteer.com/placerat/ante/nulla/justo.html?curabitur=orci&in=luctus&libero=et&ut=ultrices&massa=posuere&volutpat=cubilia&convallis=curae&morbi=donec&odio=pharetra&odio=magna&elementum=vestibulum&eu=aliquet&interdum=ultrices', '2025-10-30 04:58:07', '2025-02-19 10:34:46', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (71, 41, null, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.', 3.59, null, 'https://privacy.gov.au/orci/pede/venenatis/non/sodales/sed/tincidunt.jsp?nibh=nisl&in=duis&lectus=ac&pellentesque=nibh&at=fusce&nulla=lacus&suspendisse=purus&potenti=aliquet&cras=at&in=feugiat&purus=non&eu=pretium&magna=quis&vulputate=lectus&luctus=suspendisse&cum=potenti&sociis=in&natoque=eleifend&penatibus=quam&et=a&magnis=odio&dis=in&parturient=hac&montes=habitasse&nascetur=platea&ridiculus=dictumst&mus=maecenas&vivamus=ut&vestibulum=massa&sagittis=quis&sapien=augue&cum=luctus&sociis=tincidunt&natoque=nulla&penatibus=mollis&et=molestie&magnis=lorem&dis=quisque', '2024-12-14 17:49:29', '2025-02-03 17:18:36', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (100, 6, null, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 9.90, null, 'http://huffingtonpost.com/montes/nascetur/ridiculus/mus/etiam/vel.json?dictumst=felis&etiam=fusce&faucibus=posuere&cursus=felis&urna=sed&ut=lacus&tellus=morbi&nulla=sem&ut=mauris&erat=laoreet&id=ut&mauris=rhoncus&vulputate=aliquet&elementum=pulvinar&nullam=sed&varius=nisl&nulla=nunc&facilisi=rhoncus&cras=dui&non=vel&velit=sem&nec=sed&nisi=sagittis&vulputate=nam&nonummy=congue&maecenas=risus&tincidunt=semper&lacus=porta&at=volutpat&velit=quam&vivamus=pede&vel=lobortis&nulla=ligula&eget=sit&eros=amet&elementum=eleifend&pellentesque=pede&quisque=libero&porta=quis&volutpat=orci&erat=nullam&quisque=molestie&erat=nibh&eros=in&viverra=lectus&eget=pellentesque&congue=at&eget=nulla&semper=suspendisse&rutrum=potenti', '2025-10-25 15:54:53', '2024-12-17 02:50:44', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (75, 12, null, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 6.63, null, 'http://symantec.com/in/lectus/pellentesque/at/nulla/suspendisse.xml?bibendum=dignissim&imperdiet=vestibulum&nullam=vestibulum&orci=ante&pede=ipsum&venenatis=primis&non=in&sodales=faucibus&sed=orci&tincidunt=luctus&eu=et&felis=ultrices&fusce=posuere&posuere=cubilia&felis=curae&sed=nulla&lacus=dapibus&morbi=dolor&sem=vel', '2025-11-12 16:44:08', '2025-07-19 06:11:45', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (30, 69, null, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 7.82, null, 'https://wikimedia.org/condimentum.js?nunc=sollicitudin&rhoncus=vitae&dui=consectetuer&vel=eget&sem=rutrum&sed=at&sagittis=lorem&nam=integer&congue=tincidunt&risus=ante&semper=vel&porta=ipsum&volutpat=praesent&quam=blandit&pede=lacinia&lobortis=erat&ligula=vestibulum&sit=sed&amet=magna&eleifend=at&pede=nunc&libero=commodo&quis=placerat&orci=praesent&nullam=blandit&molestie=nam&nibh=nulla&in=integer&lectus=pede&pellentesque=justo&at=lacinia&nulla=eget&suspendisse=tincidunt&potenti=eget&cras=tempus&in=vel&purus=pede&eu=morbi&magna=porttitor&vulputate=lorem&luctus=id&cum=ligula&sociis=suspendisse&natoque=ornare&penatibus=consequat&et=lectus&magnis=in&dis=est&parturient=risus&montes=auctor&nascetur=sed&ridiculus=tristique&mus=in&vivamus=tempus&vestibulum=sit&sagittis=amet&sapien=sem&cum=fusce&sociis=consequat&natoque=nulla&penatibus=nisl&et=nunc&magnis=nisl&dis=duis&parturient=bibendum&montes=felis&nascetur=sed&ridiculus=interdum&mus=venenatis&etiam=turpis&vel=enim&augue=blandit&vestibulum=mi&rutrum=in&rutrum=porttitor&neque=pede', '2024-12-21 17:45:46', '2025-01-01 12:11:32', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (20, 40, null, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 9.31, null, 'https://nasa.gov/sed/augue/aliquam/erat/volutpat/in/congue.json?sapien=elementum&dignissim=eu&vestibulum=interdum&vestibulum=eu&ante=tincidunt&ipsum=in&primis=leo&in=maecenas&faucibus=pulvinar&orci=lobortis&luctus=est&et=phasellus&ultrices=sit&posuere=amet&cubilia=erat&curae=nulla&nulla=tempus&dapibus=vivamus&dolor=in&vel=felis&est=eu&donec=sapien&odio=cursus&justo=vestibulum&sollicitudin=proin', '2025-10-04 13:56:31', '2025-07-24 07:07:52', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (53, 75, null, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 6.84, null, 'https://twitter.com/quam.js?dapibus=mollis&duis=molestie&at=lorem&velit=quisque&eu=ut&est=erat&congue=curabitur&elementum=gravida&in=nisi&hac=at&habitasse=nibh&platea=in&dictumst=hac&morbi=habitasse&vestibulum=platea&velit=dictumst&id=aliquam&pretium=augue&iaculis=quam&diam=sollicitudin&erat=vitae&fermentum=consectetuer&justo=eget&nec=rutrum&condimentum=at&neque=lorem&sapien=integer&placerat=tincidunt&ante=ante&nulla=vel&justo=ipsum&aliquam=praesent&quis=blandit&turpis=lacinia&eget=erat&elit=vestibulum&sodales=sed&scelerisque=magna&mauris=at&sit=nunc&amet=commodo&eros=placerat&suspendisse=praesent&accumsan=blandit&tortor=nam&quis=nulla&turpis=integer&sed=pede&ante=justo&vivamus=lacinia&tortor=eget&duis=tincidunt&mattis=eget&egestas=tempus&metus=vel&aenean=pede&fermentum=morbi&donec=porttitor&ut=lorem&mauris=id&eget=ligula&massa=suspendisse&tempor=ornare&convallis=consequat&nulla=lectus&neque=in&libero=est&convallis=risus&eget=auctor&eleifend=sed&luctus=tristique&ultricies=in&eu=tempus&nibh=sit&quisque=amet&id=sem&justo=fusce&sit=consequat&amet=nulla&sapien=nisl&dignissim=nunc&vestibulum=nisl&vestibulum=duis&ante=bibendum&ipsum=felis&primis=sed&in=interdum&faucibus=venenatis&orci=turpis&luctus=enim', '2025-04-10 04:42:50', '2025-03-11 02:45:22', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (67, 84, null, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 5.78, null, 'https://123-reg.co.uk/aliquam/lacus/morbi/quis.aspx?nibh=ipsum&quisque=dolor&id=sit&justo=amet&sit=consectetuer&amet=adipiscing&sapien=elit&dignissim=proin&vestibulum=interdum&vestibulum=mauris&ante=non&ipsum=ligula&primis=pellentesque&in=ultrices&faucibus=phasellus&orci=id&luctus=sapien&et=in&ultrices=sapien&posuere=iaculis&cubilia=congue&curae=vivamus&nulla=metus&dapibus=arcu&dolor=adipiscing&vel=molestie&est=hendrerit&donec=at&odio=vulputate&justo=vitae&sollicitudin=nisl&ut=aenean&suscipit=lectus&a=pellentesque&feugiat=eget&et=nunc&eros=donec&vestibulum=quis&ac=orci&est=eget&lacinia=orci&nisi=vehicula&venenatis=condimentum&tristique=curabitur&fusce=in&congue=libero&diam=ut&id=massa&ornare=volutpat&imperdiet=convallis', '2025-07-26 15:58:18', '2025-06-02 09:58:06', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (21, 95, null, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 6.49, null, 'http://g.co/ridiculus/mus/etiam/vel/augue.html?sapien=donec&cursus=semper&vestibulum=sapien&proin=a&eu=libero&mi=nam&nulla=dui&ac=proin&enim=leo&in=odio&tempor=porttitor&turpis=id&nec=consequat&euismod=in&scelerisque=consequat&quam=ut&turpis=nulla&adipiscing=sed&lorem=accumsan&vitae=felis&mattis=ut&nibh=at&ligula=dolor&nec=quis&sem=odio&duis=consequat&aliquam=varius&convallis=integer&nunc=ac&proin=leo&at=pellentesque&turpis=ultrices&a=mattis', '2025-06-21 05:05:28', '2025-01-21 07:14:25', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (26, 40, null, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 4.35, null, 'http://answers.com/aliquet.jpg?lobortis=quisque&convallis=ut&tortor=erat&risus=curabitur&dapibus=gravida&augue=nisi&vel=at&accumsan=nibh&tellus=in&nisi=hac&eu=habitasse&orci=platea&mauris=dictumst&lacinia=aliquam&sapien=augue&quis=quam&libero=sollicitudin&nullam=vitae&sit=consectetuer&amet=eget&turpis=rutrum&elementum=at&ligula=lorem&vehicula=integer&consequat=tincidunt&morbi=ante&a=vel&ipsum=ipsum&integer=praesent&a=blandit&nibh=lacinia&in=erat&quis=vestibulum&justo=sed&maecenas=magna&rhoncus=at&aliquam=nunc&lacus=commodo&morbi=placerat&quis=praesent&tortor=blandit&id=nam&nulla=nulla&ultrices=integer&aliquet=pede&maecenas=justo&leo=lacinia&odio=eget&condimentum=tincidunt&id=eget&luctus=tempus&nec=vel&molestie=pede&sed=morbi&justo=porttitor&pellentesque=lorem&viverra=id&pede=ligula&ac=suspendisse&diam=ornare&cras=consequat&pellentesque=lectus&volutpat=in&dui=est&maecenas=risus&tristique=auctor&est=sed&et=tristique&tempus=in&semper=tempus&est=sit&quam=amet&pharetra=sem&magna=fusce&ac=consequat&consequat=nulla&metus=nisl&sapien=nunc&ut=nisl&nunc=duis&vestibulum=bibendum&ante=felis&ipsum=sed&primis=interdum&in=venenatis&faucibus=turpis&orci=enim&luctus=blandit&et=mi&ultrices=in&posuere=porttitor&cubilia=pede&curae=justo&mauris=eu&viverra=massa&diam=donec', '2025-10-22 02:40:08', '2025-01-28 03:45:02', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (67, 10, null, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 6.47, null, 'http://com.com/gravida/nisi/at/nibh/in/hac/habitasse.xml?vulputate=suspendisse&luctus=potenti&cum=cras&sociis=in&natoque=purus&penatibus=eu&et=magna&magnis=vulputate&dis=luctus&parturient=cum&montes=sociis&nascetur=natoque&ridiculus=penatibus&mus=et&vivamus=magnis&vestibulum=dis&sagittis=parturient&sapien=montes&cum=nascetur&sociis=ridiculus&natoque=mus&penatibus=vivamus&et=vestibulum&magnis=sagittis&dis=sapien&parturient=cum&montes=sociis&nascetur=natoque&ridiculus=penatibus&mus=et&etiam=magnis&vel=dis&augue=parturient&vestibulum=montes&rutrum=nascetur&rutrum=ridiculus&neque=mus&aenean=etiam&auctor=vel&gravida=augue&sem=vestibulum&praesent=rutrum&id=rutrum&massa=neque&id=aenean&nisl=auctor&venenatis=gravida&lacinia=sem&aenean=praesent', '2024-12-12 00:14:42', '2025-04-06 15:20:53', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (38, 94, null, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 9.79, null, 'http://ow.ly/lorem/ipsum/dolor/sit/amet/consectetuer.jsp?curae=at&duis=dolor&faucibus=quis&accumsan=odio&odio=consequat&curabitur=varius&convallis=integer&duis=ac&consequat=leo&dui=pellentesque&nec=ultrices&nisi=mattis&volutpat=odio&eleifend=donec&donec=vitae&ut=nisi&dolor=nam&morbi=ultrices', '2025-08-03 05:04:48', '2025-01-30 13:39:39', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (28, 49, null, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 3.27, null, 'http://vk.com/potenti/in/eleifend/quam/a.jpg?et=mi&ultrices=pede', '2025-01-22 15:21:03', '2025-11-28 22:06:41', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (66, 99, null, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 6.24, null, 'https://ycombinator.com/convallis.jpg?convallis=primis&duis=in&consequat=faucibus&dui=orci&nec=luctus&nisi=et&volutpat=ultrices', '2025-11-03 03:23:53', '2024-12-17 16:24:36', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (25, 98, null, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1.04, null, 'https://acquirethisname.com/cras/mi/pede/malesuada/in/imperdiet.png?etiam=nulla&justo=tempus&etiam=vivamus&pretium=in&iaculis=felis&justo=eu&in=sapien&hac=cursus&habitasse=vestibulum&platea=proin&dictumst=eu&etiam=mi&faucibus=nulla&cursus=ac&urna=enim&ut=in&tellus=tempor&nulla=turpis&ut=nec&erat=euismod&id=scelerisque&mauris=quam&vulputate=turpis&elementum=adipiscing&nullam=lorem&varius=vitae&nulla=mattis&facilisi=nibh&cras=ligula&non=nec&velit=sem&nec=duis&nisi=aliquam&vulputate=convallis&nonummy=nunc&maecenas=proin&tincidunt=at&lacus=turpis&at=a&velit=pede&vivamus=posuere&vel=nonummy&nulla=integer', '2025-09-20 06:12:58', '2025-06-24 00:18:20', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (23, 2, null, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 4.75, null, 'http://mozilla.org/justo/maecenas/rhoncus/aliquam/lacus/morbi.json?duis=morbi&aliquam=non&convallis=quam&nunc=nec&proin=dui&at=luctus&turpis=rutrum&a=nulla&pede=tellus&posuere=in&nonummy=sagittis&integer=dui&non=vel&velit=nisl&donec=duis&diam=ac&neque=nibh&vestibulum=fusce&eget=lacus&vulputate=purus&ut=aliquet&ultrices=at&vel=feugiat&augue=non&vestibulum=pretium&ante=quis&ipsum=lectus&primis=suspendisse&in=potenti&faucibus=in&orci=eleifend&luctus=quam&et=a&ultrices=odio&posuere=in&cubilia=hac&curae=habitasse&donec=platea&pharetra=dictumst&magna=maecenas&vestibulum=ut&aliquet=massa&ultrices=quis&erat=augue&tortor=luctus&sollicitudin=tincidunt&mi=nulla&sit=mollis&amet=molestie&lobortis=lorem&sapien=quisque&sapien=ut&non=erat&mi=curabitur&integer=gravida&ac=nisi&neque=at&duis=nibh&bibendum=in&morbi=hac&non=habitasse&quam=platea&nec=dictumst&dui=aliquam&luctus=augue&rutrum=quam&nulla=sollicitudin', '2024-12-11 17:06:40', '2025-05-13 12:01:30', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (31, 93, null, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 2.36, null, 'http://netlog.com/cum/sociis/natoque/penatibus/et.aspx?praesent=pretium&blandit=nisl&nam=ut&nulla=volutpat&integer=sapien&pede=arcu&justo=sed&lacinia=augue&eget=aliquam&tincidunt=erat&eget=volutpat&tempus=in&vel=congue&pede=etiam&morbi=justo&porttitor=etiam&lorem=pretium&id=iaculis&ligula=justo&suspendisse=in&ornare=hac&consequat=habitasse&lectus=platea&in=dictumst&est=etiam&risus=faucibus&auctor=cursus&sed=urna&tristique=ut&in=tellus&tempus=nulla&sit=ut&amet=erat&sem=id&fusce=mauris&consequat=vulputate&nulla=elementum&nisl=nullam&nunc=varius&nisl=nulla&duis=facilisi&bibendum=cras&felis=non&sed=velit&interdum=nec&venenatis=nisi&turpis=vulputate&enim=nonummy&blandit=maecenas&mi=tincidunt&in=lacus&porttitor=at&pede=velit&justo=vivamus&eu=vel&massa=nulla&donec=eget&dapibus=eros&duis=elementum&at=pellentesque&velit=quisque&eu=porta&est=volutpat&congue=erat', '2025-09-30 03:32:24', '2025-05-17 08:11:33', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (32, 71, null, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 7.00, null, 'https://europa.eu/nunc/purus/phasellus.jsp?aliquet=orci&at=nullam&feugiat=molestie&non=nibh&pretium=in&quis=lectus&lectus=pellentesque&suspendisse=at&potenti=nulla&in=suspendisse&eleifend=potenti&quam=cras&a=in&odio=purus&in=eu&hac=magna&habitasse=vulputate&platea=luctus&dictumst=cum', '2025-01-09 19:34:09', '2025-11-18 13:53:59', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (45, 34, null, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 2.19, null, 'http://privacy.gov.au/aliquet/massa/id/lobortis/convallis.xml?magna=vel&ac=pede&consequat=morbi&metus=porttitor&sapien=lorem&ut=id&nunc=ligula&vestibulum=suspendisse&ante=ornare&ipsum=consequat&primis=lectus&in=in&faucibus=est&orci=risus&luctus=auctor&et=sed&ultrices=tristique&posuere=in&cubilia=tempus&curae=sit&mauris=amet&viverra=sem&diam=fusce&vitae=consequat&quam=nulla&suspendisse=nisl&potenti=nunc&nullam=nisl&porttitor=duis&lacus=bibendum&at=felis&turpis=sed&donec=interdum&posuere=venenatis&metus=turpis&vitae=enim&ipsum=blandit&aliquam=mi&non=in&mauris=porttitor&morbi=pede&non=justo&lectus=eu&aliquam=massa&sit=donec&amet=dapibus&diam=duis&in=at&magna=velit&bibendum=eu&imperdiet=est&nullam=congue&orci=elementum&pede=in&venenatis=hac&non=habitasse&sodales=platea&sed=dictumst&tincidunt=morbi&eu=vestibulum&felis=velit&fusce=id&posuere=pretium&felis=iaculis&sed=diam&lacus=erat&morbi=fermentum&sem=justo', '2025-02-16 05:37:26', '2025-08-02 23:09:28', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (13, 97, null, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 0.80, null, 'http://youku.com/in.json?erat=eleifend&curabitur=quam&gravida=a&nisi=odio&at=in&nibh=hac&in=habitasse&hac=platea&habitasse=dictumst&platea=maecenas', '2025-11-16 08:03:30', '2025-05-14 14:01:42', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (82, 97, null, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 1.72, null, 'https://economist.com/maecenas/tristique/est/et/tempus/semper/est.aspx?ac=a&diam=ipsum&cras=integer&pellentesque=a&volutpat=nibh&dui=in&maecenas=quis&tristique=justo&est=maecenas&et=rhoncus&tempus=aliquam&semper=lacus&est=morbi&quam=quis&pharetra=tortor&magna=id&ac=nulla&consequat=ultrices&metus=aliquet&sapien=maecenas&ut=leo&nunc=odio&vestibulum=condimentum&ante=id&ipsum=luctus&primis=nec&in=molestie&faucibus=sed&orci=justo&luctus=pellentesque&et=viverra&ultrices=pede&posuere=ac&cubilia=diam&curae=cras&mauris=pellentesque&viverra=volutpat&diam=dui&vitae=maecenas&quam=tristique&suspendisse=est&potenti=et&nullam=tempus&porttitor=semper&lacus=est&at=quam&turpis=pharetra&donec=magna&posuere=ac&metus=consequat&vitae=metus&ipsum=sapien&aliquam=ut&non=nunc&mauris=vestibulum&morbi=ante&non=ipsum&lectus=primis&aliquam=in&sit=faucibus&amet=orci&diam=luctus&in=et&magna=ultrices&bibendum=posuere&imperdiet=cubilia&nullam=curae&orci=mauris&pede=viverra&venenatis=diam&non=vitae&sodales=quam', '2025-03-12 00:42:39', '2025-08-07 18:25:37', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (35, 75, null, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 5.44, null, 'http://domainmarket.com/augue/aliquam/erat/volutpat/in/congue.xml?eleifend=et&pede=ultrices&libero=posuere&quis=cubilia&orci=curae&nullam=mauris&molestie=viverra&nibh=diam&in=vitae&lectus=quam&pellentesque=suspendisse&at=potenti&nulla=nullam&suspendisse=porttitor&potenti=lacus&cras=at&in=turpis&purus=donec&eu=posuere&magna=metus&vulputate=vitae&luctus=ipsum&cum=aliquam&sociis=non&natoque=mauris&penatibus=morbi&et=non&magnis=lectus&dis=aliquam&parturient=sit&montes=amet&nascetur=diam&ridiculus=in&mus=magna&vivamus=bibendum&vestibulum=imperdiet&sagittis=nullam&sapien=orci&cum=pede&sociis=venenatis&natoque=non&penatibus=sodales&et=sed&magnis=tincidunt&dis=eu&parturient=felis&montes=fusce&nascetur=posuere&ridiculus=felis&mus=sed&etiam=lacus&vel=morbi&augue=sem&vestibulum=mauris&rutrum=laoreet&rutrum=ut&neque=rhoncus&aenean=aliquet&auctor=pulvinar&gravida=sed&sem=nisl&praesent=nunc&id=rhoncus&massa=dui&id=vel&nisl=sem&venenatis=sed&lacinia=sagittis&aenean=nam&sit=congue&amet=risus&justo=semper&morbi=porta&ut=volutpat&odio=quam&cras=pede&mi=lobortis&pede=ligula&malesuada=sit&in=amet&imperdiet=eleifend&et=pede&commodo=libero&vulputate=quis&justo=orci&in=nullam&blandit=molestie', '2025-07-07 01:44:23', '2025-10-06 22:42:54', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (77, 97, null, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 5.85, null, 'https://dmoz.org/integer/ac/leo/pellentesque/ultrices/mattis/odio.js?pellentesque=in&viverra=ante&pede=vestibulum&ac=ante&diam=ipsum&cras=primis&pellentesque=in&volutpat=faucibus&dui=orci&maecenas=luctus&tristique=et&est=ultrices&et=posuere&tempus=cubilia&semper=curae&est=duis&quam=faucibus&pharetra=accumsan&magna=odio&ac=curabitur&consequat=convallis&metus=duis&sapien=consequat&ut=dui&nunc=nec&vestibulum=nisi&ante=volutpat&ipsum=eleifend&primis=donec&in=ut&faucibus=dolor&orci=morbi&luctus=vel&et=lectus&ultrices=in&posuere=quam&cubilia=fringilla&curae=rhoncus&mauris=mauris&viverra=enim&diam=leo&vitae=rhoncus&quam=sed&suspendisse=vestibulum&potenti=sit&nullam=amet&porttitor=cursus&lacus=id&at=turpis&turpis=integer&donec=aliquet&posuere=massa&metus=id&vitae=lobortis&ipsum=convallis&aliquam=tortor&non=risus&mauris=dapibus&morbi=augue&non=vel&lectus=accumsan&aliquam=tellus&sit=nisi&amet=eu&diam=orci&in=mauris&magna=lacinia&bibendum=sapien&imperdiet=quis&nullam=libero&orci=nullam&pede=sit&venenatis=amet&non=turpis&sodales=elementum&sed=ligula&tincidunt=vehicula&eu=consequat&felis=morbi&fusce=a&posuere=ipsum&felis=integer&sed=a&lacus=nibh&morbi=in&sem=quis&mauris=justo&laoreet=maecenas&ut=rhoncus&rhoncus=aliquam&aliquet=lacus&pulvinar=morbi&sed=quis&nisl=tortor&nunc=id&rhoncus=nulla&dui=ultrices', '2024-12-21 18:10:51', '2025-07-25 09:13:00', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (11, 95, null, 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1.74, null, 'http://hatena.ne.jp/vitae/quam.js?vestibulum=purus&vestibulum=eu&ante=magna&ipsum=vulputate&primis=luctus&in=cum&faucibus=sociis', '2025-07-26 12:29:56', '2025-04-20 02:56:26', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (53, 20, null, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.', 0.98, null, 'http://163.com/curabitur/at.png?platea=orci&dictumst=nullam&morbi=molestie&vestibulum=nibh&velit=in&id=lectus&pretium=pellentesque&iaculis=at&diam=nulla&erat=suspendisse&fermentum=potenti&justo=cras&nec=in&condimentum=purus&neque=eu&sapien=magna&placerat=vulputate&ante=luctus&nulla=cum&justo=sociis&aliquam=natoque&quis=penatibus&turpis=et&eget=magnis&elit=dis&sodales=parturient&scelerisque=montes&mauris=nascetur&sit=ridiculus&amet=mus&eros=vivamus&suspendisse=vestibulum&accumsan=sagittis&tortor=sapien&quis=cum&turpis=sociis&sed=natoque&ante=penatibus&vivamus=et&tortor=magnis&duis=dis&mattis=parturient&egestas=montes&metus=nascetur&aenean=ridiculus&fermentum=mus&donec=etiam&ut=vel&mauris=augue&eget=vestibulum&massa=rutrum&tempor=rutrum&convallis=neque&nulla=aenean&neque=auctor&libero=gravida&convallis=sem&eget=praesent&eleifend=id&luctus=massa&ultricies=id&eu=nisl&nibh=venenatis&quisque=lacinia', '2025-11-05 11:24:59', '2025-01-16 14:22:19', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (68, 93, null, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 3.17, null, 'https://skyrock.com/tristique.xml?odio=nullam&condimentum=molestie&id=nibh&luctus=in&nec=lectus&molestie=pellentesque&sed=at&justo=nulla&pellentesque=suspendisse&viverra=potenti&pede=cras&ac=in&diam=purus&cras=eu&pellentesque=magna&volutpat=vulputate&dui=luctus&maecenas=cum&tristique=sociis&est=natoque&et=penatibus&tempus=et&semper=magnis&est=dis&quam=parturient&pharetra=montes', '2025-09-03 03:15:45', '2025-10-08 19:10:46', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (55, 44, null, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 0.71, null, 'http://toplist.cz/faucibus/accumsan/odio/curabitur.js?lacinia=donec&sapien=posuere&quis=metus&libero=vitae&nullam=ipsum&sit=aliquam&amet=non&turpis=mauris&elementum=morbi&ligula=non&vehicula=lectus&consequat=aliquam&morbi=sit&a=amet&ipsum=diam&integer=in&a=magna&nibh=bibendum', '2025-04-09 05:13:54', '2025-09-05 04:10:57', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (17, 4, null, 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 6.38, null, 'https://vinaora.com/duis/faucibus/accumsan/odio/curabitur.jsp?faucibus=varius&orci=nulla&luctus=facilisi&et=cras&ultrices=non&posuere=velit&cubilia=nec&curae=nisi&mauris=vulputate&viverra=nonummy&diam=maecenas&vitae=tincidunt&quam=lacus&suspendisse=at&potenti=velit&nullam=vivamus&porttitor=vel&lacus=nulla&at=eget&turpis=eros&donec=elementum&posuere=pellentesque&metus=quisque&vitae=porta&ipsum=volutpat&aliquam=erat&non=quisque&mauris=erat&morbi=eros&non=viverra&lectus=eget&aliquam=congue&sit=eget&amet=semper&diam=rutrum&in=nulla&magna=nunc&bibendum=purus&imperdiet=phasellus&nullam=in&orci=felis&pede=donec&venenatis=semper&non=sapien&sodales=a', '2025-01-12 15:24:15', '2025-07-28 20:04:13', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (75, 50, null, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1.86, null, 'http://google.com.br/dictumst/maecenas.json?interdum=dolor&venenatis=quis&turpis=odio&enim=consequat&blandit=varius&mi=integer&in=ac&porttitor=leo&pede=pellentesque&justo=ultrices&eu=mattis&massa=odio&donec=donec&dapibus=vitae&duis=nisi&at=nam&velit=ultrices&eu=libero&est=non&congue=mattis&elementum=pulvinar&in=nulla&hac=pede&habitasse=ullamcorper&platea=augue&dictumst=a&morbi=suscipit&vestibulum=nulla&velit=elit&id=ac&pretium=nulla&iaculis=sed&diam=vel&erat=enim&fermentum=sit&justo=amet&nec=nunc&condimentum=viverra&neque=dapibus&sapien=nulla&placerat=suscipit&ante=ligula&nulla=in', '2025-11-24 10:14:58', '2024-12-24 00:17:55', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (87, 74, null, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 8.28, null, 'https://oaic.gov.au/ac/leo/pellentesque/ultrices/mattis.xml?in=rhoncus&est=mauris&risus=enim&auctor=leo&sed=rhoncus&tristique=sed&in=vestibulum&tempus=sit&sit=amet&amet=cursus&sem=id&fusce=turpis&consequat=integer&nulla=aliquet&nisl=massa&nunc=id&nisl=lobortis&duis=convallis&bibendum=tortor&felis=risus&sed=dapibus&interdum=augue&venenatis=vel&turpis=accumsan&enim=tellus&blandit=nisi&mi=eu&in=orci&porttitor=mauris&pede=lacinia&justo=sapien&eu=quis&massa=libero&donec=nullam&dapibus=sit&duis=amet&at=turpis&velit=elementum&eu=ligula&est=vehicula&congue=consequat&elementum=morbi&in=a&hac=ipsum&habitasse=integer&platea=a&dictumst=nibh&morbi=in&vestibulum=quis&velit=justo&id=maecenas&pretium=rhoncus&iaculis=aliquam&diam=lacus&erat=morbi&fermentum=quis&justo=tortor&nec=id&condimentum=nulla&neque=ultrices&sapien=aliquet&placerat=maecenas', '2025-03-03 13:42:13', '2025-12-03 09:01:30', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (27, 95, null, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 6.02, null, 'http://engadget.com/nibh/fusce/lacus.png?eu=hac&tincidunt=habitasse&in=platea&leo=dictumst&maecenas=etiam&pulvinar=faucibus&lobortis=cursus&est=urna&phasellus=ut&sit=tellus&amet=nulla&erat=ut&nulla=erat&tempus=id&vivamus=mauris&in=vulputate&felis=elementum&eu=nullam&sapien=varius&cursus=nulla&vestibulum=facilisi&proin=cras&eu=non&mi=velit&nulla=nec&ac=nisi&enim=vulputate&in=nonummy&tempor=maecenas&turpis=tincidunt&nec=lacus&euismod=at&scelerisque=velit&quam=vivamus&turpis=vel&adipiscing=nulla&lorem=eget&vitae=eros&mattis=elementum&nibh=pellentesque&ligula=quisque&nec=porta&sem=volutpat&duis=erat&aliquam=quisque&convallis=erat&nunc=eros&proin=viverra&at=eget&turpis=congue&a=eget&pede=semper&posuere=rutrum&nonummy=nulla&integer=nunc&non=purus&velit=phasellus&donec=in&diam=felis&neque=donec&vestibulum=semper&eget=sapien&vulputate=a', '2025-02-28 20:12:36', '2025-07-04 03:47:42', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (70, 60, null, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 2.08, null, 'http://gizmodo.com/ipsum.png?in=orci&porttitor=pede&pede=venenatis&justo=non&eu=sodales&massa=sed&donec=tincidunt&dapibus=eu&duis=felis&at=fusce&velit=posuere&eu=felis&est=sed&congue=lacus&elementum=morbi&in=sem&hac=mauris&habitasse=laoreet&platea=ut&dictumst=rhoncus&morbi=aliquet&vestibulum=pulvinar&velit=sed&id=nisl&pretium=nunc&iaculis=rhoncus&diam=dui&erat=vel&fermentum=sem&justo=sed&nec=sagittis&condimentum=nam&neque=congue&sapien=risus&placerat=semper&ante=porta&nulla=volutpat&justo=quam&aliquam=pede&quis=lobortis&turpis=ligula&eget=sit&elit=amet&sodales=eleifend&scelerisque=pede&mauris=libero&sit=quis&amet=orci&eros=nullam&suspendisse=molestie&accumsan=nibh&tortor=in&quis=lectus&turpis=pellentesque&sed=at&ante=nulla&vivamus=suspendisse&tortor=potenti&duis=cras&mattis=in&egestas=purus&metus=eu&aenean=magna&fermentum=vulputate&donec=luctus&ut=cum&mauris=sociis&eget=natoque&massa=penatibus&tempor=et', '2025-02-25 15:07:35', '2025-02-19 00:52:44', 'inactive');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (55, 26, null, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1.15, null, 'http://google.es/dictumst/aliquam/augue/quam/sollicitudin/vitae/consectetuer.js?ac=morbi&enim=odio&in=odio&tempor=elementum&turpis=eu&nec=interdum&euismod=eu&scelerisque=tincidunt&quam=in&turpis=leo&adipiscing=maecenas&lorem=pulvinar&vitae=lobortis&mattis=est&nibh=phasellus&ligula=sit&nec=amet&sem=erat&duis=nulla&aliquam=tempus&convallis=vivamus&nunc=in&proin=felis&at=eu&turpis=sapien&a=cursus&pede=vestibulum&posuere=proin&nonummy=eu&integer=mi&non=nulla&velit=ac&donec=enim&diam=in&neque=tempor&vestibulum=turpis&eget=nec&vulputate=euismod&ut=scelerisque&ultrices=quam&vel=turpis&augue=adipiscing&vestibulum=lorem&ante=vitae&ipsum=mattis&primis=nibh&in=ligula&faucibus=nec&orci=sem&luctus=duis&et=aliquam&ultrices=convallis&posuere=nunc&cubilia=proin&curae=at&donec=turpis&pharetra=a&magna=pede&vestibulum=posuere&aliquet=nonummy&ultrices=integer&erat=non&tortor=velit&sollicitudin=donec&mi=diam&sit=neque&amet=vestibulum&lobortis=eget&sapien=vulputate&sapien=ut&non=ultrices&mi=vel&integer=augue&ac=vestibulum&neque=ante&duis=ipsum&bibendum=primis&morbi=in&non=faucibus&quam=orci&nec=luctus&dui=et&luctus=ultrices&rutrum=posuere&nulla=cubilia&tellus=curae&in=donec&sagittis=pharetra&dui=magna&vel=vestibulum&nisl=aliquet&duis=ultrices&ac=erat&nibh=tortor&fusce=sollicitudin', '2025-01-08 06:05:04', '2025-05-31 21:40:00', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (26, 37, null, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 2.70, null, 'http://jiathis.com/pede.js?nunc=ligula&viverra=vehicula&dapibus=consequat&nulla=morbi&suscipit=a&ligula=ipsum&in=integer&lacus=a&curabitur=nibh&at=in&ipsum=quis&ac=justo&tellus=maecenas&semper=rhoncus&interdum=aliquam&mauris=lacus&ullamcorper=morbi&purus=quis&sit=tortor&amet=id&nulla=nulla&quisque=ultrices&arcu=aliquet&libero=maecenas&rutrum=leo&ac=odio&lobortis=condimentum&vel=id', '2025-03-24 18:16:24', '2025-08-02 09:53:01', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (50, 41, null, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 3.03, null, 'http://tmall.com/nibh/fusce/lacus.xml?etiam=tortor&faucibus=id&cursus=nulla&urna=ultrices&ut=aliquet&tellus=maecenas&nulla=leo&ut=odio&erat=condimentum&id=id&mauris=luctus&vulputate=nec&elementum=molestie&nullam=sed&varius=justo&nulla=pellentesque&facilisi=viverra&cras=pede&non=ac&velit=diam&nec=cras&nisi=pellentesque&vulputate=volutpat&nonummy=dui&maecenas=maecenas&tincidunt=tristique&lacus=est&at=et&velit=tempus&vivamus=semper&vel=est&nulla=quam&eget=pharetra&eros=magna&elementum=ac&pellentesque=consequat&quisque=metus&porta=sapien&volutpat=ut&erat=nunc&quisque=vestibulum&erat=ante&eros=ipsum&viverra=primis&eget=in&congue=faucibus&eget=orci&semper=luctus&rutrum=et&nulla=ultrices&nunc=posuere&purus=cubilia&phasellus=curae&in=mauris&felis=viverra&donec=diam&semper=vitae&sapien=quam&a=suspendisse&libero=potenti&nam=nullam&dui=porttitor&proin=lacus&leo=at&odio=turpis&porttitor=donec&id=posuere&consequat=metus&in=vitae&consequat=ipsum&ut=aliquam&nulla=non&sed=mauris&accumsan=morbi&felis=non&ut=lectus&at=aliquam&dolor=sit&quis=amet&odio=diam&consequat=in&varius=magna&integer=bibendum&ac=imperdiet&leo=nullam', '2025-11-29 13:53:08', '2025-03-04 13:34:25', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (33, 44, null, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 8.44, null, 'http://google.ru/vivamus/vel/nulla/eget.aspx?vivamus=in&metus=porttitor&arcu=pede&adipiscing=justo&molestie=eu&hendrerit=massa&at=donec&vulputate=dapibus&vitae=duis&nisl=at&aenean=velit&lectus=eu&pellentesque=est&eget=congue&nunc=elementum&donec=in&quis=hac&orci=habitasse&eget=platea&orci=dictumst&vehicula=morbi&condimentum=vestibulum&curabitur=velit&in=id&libero=pretium&ut=iaculis&massa=diam&volutpat=erat&convallis=fermentum&morbi=justo&odio=nec&odio=condimentum&elementum=neque&eu=sapien&interdum=placerat&eu=ante&tincidunt=nulla&in=justo&leo=aliquam&maecenas=quis&pulvinar=turpis&lobortis=eget&est=elit&phasellus=sodales&sit=scelerisque&amet=mauris&erat=sit&nulla=amet&tempus=eros&vivamus=suspendisse&in=accumsan&felis=tortor&eu=quis&sapien=turpis&cursus=sed&vestibulum=ante&proin=vivamus&eu=tortor&mi=duis&nulla=mattis&ac=egestas&enim=metus&in=aenean&tempor=fermentum&turpis=donec&nec=ut&euismod=mauris&scelerisque=eget&quam=massa&turpis=tempor&adipiscing=convallis&lorem=nulla&vitae=neque&mattis=libero&nibh=convallis&ligula=eget&nec=eleifend&sem=luctus&duis=ultricies&aliquam=eu&convallis=nibh&nunc=quisque&proin=id&at=justo&turpis=sit&a=amet&pede=sapien&posuere=dignissim&nonummy=vestibulum&integer=vestibulum&non=ante&velit=ipsum&donec=primis&diam=in&neque=faucibus&vestibulum=orci&eget=luctus&vulputate=et', '2025-05-27 21:17:13', '2025-04-27 14:41:52', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (30, 92, null, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 7.90, null, 'https://mediafire.com/sem/fusce/consequat/nulla.html?mi=dictumst&integer=etiam&ac=faucibus&neque=cursus&duis=urna&bibendum=ut&morbi=tellus&non=nulla&quam=ut&nec=erat&dui=id&luctus=mauris&rutrum=vulputate&nulla=elementum&tellus=nullam&in=varius&sagittis=nulla&dui=facilisi&vel=cras&nisl=non&duis=velit&ac=nec&nibh=nisi&fusce=vulputate&lacus=nonummy&purus=maecenas&aliquet=tincidunt&at=lacus&feugiat=at&non=velit&pretium=vivamus&quis=vel&lectus=nulla&suspendisse=eget&potenti=eros&in=elementum&eleifend=pellentesque&quam=quisque&a=porta&odio=volutpat&in=erat&hac=quisque&habitasse=erat&platea=eros&dictumst=viverra&maecenas=eget&ut=congue&massa=eget&quis=semper&augue=rutrum&luctus=nulla&tincidunt=nunc&nulla=purus&mollis=phasellus&molestie=in&lorem=felis&quisque=donec&ut=semper&erat=sapien&curabitur=a&gravida=libero&nisi=nam&at=dui&nibh=proin', '2025-09-11 08:53:58', '2025-03-19 19:12:01', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (69, 8, null, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 9.63, null, 'https://tuttocitta.it/pulvinar.html?molestie=mollis&lorem=molestie&quisque=lorem&ut=quisque&erat=ut&curabitur=erat&gravida=curabitur&nisi=gravida&at=nisi&nibh=at&in=nibh&hac=in&habitasse=hac&platea=habitasse&dictumst=platea&aliquam=dictumst&augue=aliquam&quam=augue&sollicitudin=quam&vitae=sollicitudin&consectetuer=vitae&eget=consectetuer&rutrum=eget&at=rutrum&lorem=at&integer=lorem&tincidunt=integer&ante=tincidunt&vel=ante&ipsum=vel&praesent=ipsum&blandit=praesent&lacinia=blandit&erat=lacinia&vestibulum=erat&sed=vestibulum&magna=sed&at=magna&nunc=at&commodo=nunc&placerat=commodo&praesent=placerat&blandit=praesent&nam=blandit&nulla=nam&integer=nulla', '2025-04-28 10:12:51', '2025-07-30 14:49:18', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (72, 54, null, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 7.51, null, 'http://ftc.gov/quam/sapien/varius.html?aliquet=sit&at=amet&feugiat=justo&non=morbi&pretium=ut&quis=odio&lectus=cras&suspendisse=mi&potenti=pede&in=malesuada&eleifend=in&quam=imperdiet&a=et&odio=commodo&in=vulputate&hac=justo&habitasse=in&platea=blandit&dictumst=ultrices&maecenas=enim&ut=lorem&massa=ipsum&quis=dolor&augue=sit&luctus=amet&tincidunt=consectetuer&nulla=adipiscing&mollis=elit&molestie=proin&lorem=interdum&quisque=mauris&ut=non&erat=ligula&curabitur=pellentesque&gravida=ultrices&nisi=phasellus&at=id&nibh=sapien&in=in&hac=sapien&habitasse=iaculis&platea=congue&dictumst=vivamus&aliquam=metus&augue=arcu&quam=adipiscing&sollicitudin=molestie&vitae=hendrerit&consectetuer=at&eget=vulputate&rutrum=vitae&at=nisl&lorem=aenean&integer=lectus&tincidunt=pellentesque&ante=eget&vel=nunc&ipsum=donec&praesent=quis&blandit=orci&lacinia=eget&erat=orci&vestibulum=vehicula&sed=condimentum&magna=curabitur&at=in&nunc=libero&commodo=ut&placerat=massa&praesent=volutpat&blandit=convallis&nam=morbi&nulla=odio&integer=odio&pede=elementum&justo=eu&lacinia=interdum&eget=eu&tincidunt=tincidunt&eget=in&tempus=leo&vel=maecenas&pede=pulvinar&morbi=lobortis&porttitor=est&lorem=phasellus&id=sit', '2025-07-07 00:05:52', '2025-01-14 00:58:14', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (85, 14, null, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 0.98, null, 'http://amazon.co.uk/nisl/duis.jsp?consequat=fermentum&nulla=donec&nisl=ut&nunc=mauris&nisl=eget&duis=massa&bibendum=tempor&felis=convallis&sed=nulla&interdum=neque&venenatis=libero&turpis=convallis&enim=eget&blandit=eleifend&mi=luctus&in=ultricies&porttitor=eu&pede=nibh&justo=quisque&eu=id&massa=justo&donec=sit&dapibus=amet&duis=sapien&at=dignissim&velit=vestibulum&eu=vestibulum&est=ante&congue=ipsum&elementum=primis&in=in&hac=faucibus&habitasse=orci&platea=luctus&dictumst=et&morbi=ultrices&vestibulum=posuere&velit=cubilia&id=curae&pretium=nulla&iaculis=dapibus&diam=dolor&erat=vel&fermentum=est&justo=donec&nec=odio&condimentum=justo&neque=sollicitudin&sapien=ut&placerat=suscipit&ante=a&nulla=feugiat&justo=et&aliquam=eros&quis=vestibulum&turpis=ac&eget=est&elit=lacinia&sodales=nisi&scelerisque=venenatis&mauris=tristique&sit=fusce&amet=congue&eros=diam&suspendisse=id&accumsan=ornare&tortor=imperdiet&quis=sapien&turpis=urna&sed=pretium&ante=nisl&vivamus=ut&tortor=volutpat&duis=sapien&mattis=arcu&egestas=sed&metus=augue&aenean=aliquam&fermentum=erat&donec=volutpat&ut=in&mauris=congue&eget=etiam&massa=justo&tempor=etiam&convallis=pretium&nulla=iaculis&neque=justo&libero=in&convallis=hac&eget=habitasse', '2025-05-18 18:18:23', '2025-01-25 02:35:33', 'draft');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (46, 36, null, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 9.69, null, 'https://acquirethisname.com/fusce/congue/diam/id.xml?quis=enim&justo=leo&maecenas=rhoncus&rhoncus=sed&aliquam=vestibulum&lacus=sit&morbi=amet&quis=cursus&tortor=id&id=turpis&nulla=integer&ultrices=aliquet&aliquet=massa&maecenas=id&leo=lobortis&odio=convallis&condimentum=tortor&id=risus&luctus=dapibus&nec=augue&molestie=vel&sed=accumsan&justo=tellus&pellentesque=nisi&viverra=eu&pede=orci&ac=mauris&diam=lacinia&cras=sapien&pellentesque=quis&volutpat=libero&dui=nullam&maecenas=sit&tristique=amet', '2025-09-14 20:17:22', '2025-05-13 08:21:13', 'removed');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (17, 76, null, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2.11, null, 'https://mediafire.com/enim/lorem/ipsum.jpg?molestie=lacus&sed=at&justo=turpis&pellentesque=donec&viverra=posuere&pede=metus&ac=vitae&diam=ipsum&cras=aliquam&pellentesque=non&volutpat=mauris&dui=morbi&maecenas=non&tristique=lectus&est=aliquam&et=sit&tempus=amet&semper=diam&est=in&quam=magna&pharetra=bibendum&magna=imperdiet&ac=nullam&consequat=orci&metus=pede&sapien=venenatis&ut=non&nunc=sodales&vestibulum=sed&ante=tincidunt&ipsum=eu&primis=felis&in=fusce', '2025-07-04 17:01:05', '2025-09-20 05:13:14', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (18, 69, null, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 0.95, null, 'https://kickstarter.com/lacinia.jsp?donec=luctus&diam=cum&neque=sociis&vestibulum=natoque&eget=penatibus&vulputate=et&ut=magnis&ultrices=dis&vel=parturient&augue=montes&vestibulum=nascetur&ante=ridiculus&ipsum=mus&primis=vivamus&in=vestibulum&faucibus=sagittis&orci=sapien&luctus=cum&et=sociis&ultrices=natoque&posuere=penatibus&cubilia=et&curae=magnis&donec=dis&pharetra=parturient&magna=montes&vestibulum=nascetur&aliquet=ridiculus&ultrices=mus&erat=etiam&tortor=vel&sollicitudin=augue&mi=vestibulum&sit=rutrum&amet=rutrum&lobortis=neque&sapien=aenean&sapien=auctor&non=gravida&mi=sem&integer=praesent&ac=id&neque=massa&duis=id&bibendum=nisl&morbi=venenatis&non=lacinia&quam=aenean&nec=sit&dui=amet&luctus=justo&rutrum=morbi&nulla=ut&tellus=odio&in=cras&sagittis=mi&dui=pede&vel=malesuada&nisl=in&duis=imperdiet&ac=et&nibh=commodo&fusce=vulputate&lacus=justo&purus=in&aliquet=blandit&at=ultrices&feugiat=enim&non=lorem&pretium=ipsum&quis=dolor&lectus=sit&suspendisse=amet&potenti=consectetuer', '2025-01-20 15:38:21', '2025-05-11 10:10:27', 'active');
INSERT INTO listing (categoryId, providerId, title, description, price, unit, imageUrl, createDate, lastUpdate, listingStatus) values (100, 42, null, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1.61, null, 'http://senate.gov/elit/sodales/scelerisque.aspx?leo=enim&maecenas=in&pulvinar=tempor&lobortis=turpis&est=nec&phasellus=euismod&sit=scelerisque&amet=quam&erat=turpis&nulla=adipiscing&tempus=lorem&vivamus=vitae&in=mattis&felis=nibh&eu=ligula&sapien=nec&cursus=sem&vestibulum=duis&proin=aliquam&eu=convallis&mi=nunc&nulla=proin&ac=at&enim=turpis&in=a&tempor=pede&turpis=posuere&nec=nonummy&euismod=integer&scelerisque=non&quam=velit&turpis=donec&adipiscing=diam&lorem=neque&vitae=vestibulum', '2025-04-01 15:59:39', '2025-06-07 07:35:59', 'active');
